### ISSUE TITLE
差額が少ないものは表示しない

### ISSUE THREAD

**Issue by hashiwataru** [komacchi/view-pricecheck#5]
どうじゃろうか。
3桁差額以上のものだけ表示するとか。

**Comment by komacchi** [comment]
100円差以上のものは切ります。差額は指定できるので良さげなところありますかね？

**Comment by komacchi** [comment]
差額の調整はできるので、いったんこちらcloseします

**Comment by hashiwataru** [comment]
あざますー。
100円以下とかのざっくりでよいかとー。
